"""Build and verify the durable R486 intake of post-hoc R485 analyses.

Motivation
----------
Recent project conversations produced useful sealed-data derivatives under
``tmp/``.  This probe promotes only hash-verifiable artifacts, preserves the
post-hoc/exploratory boundary, and emits one machine-readable R486 decision.

Usage
-----
``python probes/r486_r485_posthoc_intake/build_intake.py``

The command never runs ANDES, training, or evaluation.  It reads the closed
R485 result and the already-copied R486 packages, verifies their hashes and
scope, writes ``analysis.json`` plus SHA-256 sidecars, and fails closed on any
drift.  Re-running is idempotent only when the generated bytes are unchanged.
"""

from __future__ import annotations

import hashlib
import json
import math
import statistics
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
RESULT_ROOT = ROOT / "results/research_loop/r486_r485_posthoc_intake"
FORMAL_ROOT = (
    ROOT
    / "results/research_loop/r485_60hz_source_factorial"
    / "r485-formal-20260829-a"
)
FORMAL_ANALYSIS = FORMAL_ROOT / "formal_analysis.json"
TRAIN_ROOT = FORMAL_ROOT / "train"
PROBE_ROOT = ROOT / "probes/r486_r485_posthoc_intake"


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def read_json(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"expected JSON object: {path}")
    return payload


def verify_sidecar(path: Path) -> str:
    sidecar = path.with_name(path.name + ".sha256")
    if not sidecar.is_file():
        raise FileNotFoundError(f"missing sidecar: {sidecar}")
    expected = sidecar.read_text(encoding="ascii").split()[0].lower()
    actual = sha256_file(path)
    if actual != expected:
        raise ValueError(f"sidecar mismatch: {path}")
    return actual


def verify_sha256s(directory: Path) -> dict[str, str]:
    sums = directory / "SHA256SUMS"
    if not sums.is_file():
        raise FileNotFoundError(f"missing SHA256SUMS: {directory}")
    verified: dict[str, str] = {}
    for line in sums.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        fields = line.split(maxsplit=1)
        if len(fields) != 2:
            raise ValueError(f"malformed SHA256SUMS line: {line!r}")
        expected, name = fields
        path = directory / name.strip()
        if not path.is_file():
            raise FileNotFoundError(f"missing hashed file: {path}")
        actual = sha256_file(path)
        if actual != expected.lower():
            raise ValueError(f"SHA256SUMS mismatch: {path}")
        verified[name.strip()] = actual
    if not verified:
        raise ValueError(f"empty SHA256SUMS: {sums}")
    return verified


def canonical_json_bytes(payload: dict[str, Any]) -> bytes:
    return (
        json.dumps(payload, indent=2, sort_keys=True, allow_nan=False) + "\n"
    ).encode("utf-8")


def write_stable_json(path: Path, payload: dict[str, Any]) -> str:
    encoded = canonical_json_bytes(payload)
    if path.exists() and path.read_bytes() != encoded:
        raise FileExistsError(f"refusing to overwrite drifted result: {path}")
    path.write_bytes(encoded)
    digest = hashlib.sha256(encoded).hexdigest()
    sidecar = path.with_name(path.name + ".sha256")
    sidecar.write_text(f"{digest}  {path.name}\n", encoding="ascii")
    return digest


def write_json_sidecars() -> dict[str, str]:
    hashes: dict[str, str] = {}
    for path in sorted(RESULT_ROOT.rglob("*.json")):
        digest = sha256_file(path)
        sidecar = path.with_name(path.name + ".sha256")
        sidecar.write_text(f"{digest}  {path.name}\n", encoding="ascii")
        hashes[path.relative_to(RESULT_ROOT).as_posix()] = digest
    return hashes


def assert_finite(value: Any, label: str) -> None:
    if isinstance(value, bool) or value is None or isinstance(value, str):
        return
    if isinstance(value, (int, float)):
        if not math.isfinite(float(value)):
            raise ValueError(f"non-finite value at {label}: {value!r}")
        return
    if isinstance(value, list):
        for index, item in enumerate(value):
            assert_finite(item, f"{label}/{index}")
        return
    if isinstance(value, dict):
        for key, item in value.items():
            assert_finite(item, f"{label}/{key}")


def compact_bound(row: dict[str, Any]) -> dict[str, Any]:
    return {
        "horizon": row["horizon"],
        "effect": row["effect"],
        "n_seeds": row["n_seeds"],
        "ratio_estimate": row["ratio_estimate"],
        "ci95_ratio_lower": row["ci95_ratio_lower"],
        "ci95_ratio_upper": row["ci95_ratio_upper"],
        "familywise_95_ratio_upper": row["familywise_95_ratio_upper"],
        "familywise_upper_excludes_1_10": row[
            "familywise_upper_excludes_1_10"
        ],
        "status": row["post_completion_status"],
    }


def main() -> None:
    formal_hash = verify_sidecar(FORMAL_ANALYSIS)
    formal = read_json(FORMAL_ANALYSIS)
    if formal.get("status") != "VALID-MIXED":
        raise ValueError("R485 formal status drifted from VALID-MIXED")

    package_dirs = [
        RESULT_ROOT / "offline_extension",
        RESULT_ROOT / "prepaper_audit",
        RESULT_ROOT / "root_cause_synthesis",
        *[
            RESULT_ROOT / f"root_cause_probe_{index:02d}"
            for index in range(1, 11)
        ],
    ]
    package_checks = {
        path.name: verify_sha256s(path) for path in package_dirs
    }

    # Durable probe copies must remain byte-identical to the promoted snapshots.
    script_mirrors: dict[str, str] = {}
    for directory in package_dirs:
        for source in sorted(directory.glob("*.py")):
            mirror = PROBE_ROOT / source.name
            if not mirror.is_file() or sha256_file(mirror) != sha256_file(source):
                raise ValueError(f"probe mirror mismatch: {source.name}")
            script_mirrors[source.name] = sha256_file(mirror)
    offline_script = PROBE_ROOT / "r485_offline_extension.py"
    if not offline_script.is_file():
        raise FileNotFoundError(offline_script)
    script_mirrors[offline_script.name] = sha256_file(offline_script)

    offline = read_json(RESULT_ROOT / "offline_extension/analysis.json")
    prepaper = {
        f"probe{index:02d}": read_json(
            RESULT_ROOT / f"prepaper_audit/probe{index:02d}_result.json"
        )
        for index in range(1, 5)
    }
    expected_audit_decisions = {
        "probe01": "PASS_PROCEED_TO_METRIC_RECOMPUTATION",
        "probe02": "PASS_PROCEED_TO_COMPARATOR_AND_STATISTICS",
        "probe03": "PASS_PROCEED_TO_MECHANISM_AND_AUTHORITY_AUDIT",
        "probe04": "PASS_EXTENSION_NUMERICALLY_REPRODUCIBLE",
    }
    observed_audit_decisions = {
        key: value["decision"] for key, value in prepaper.items()
    }
    if observed_audit_decisions != expected_audit_decisions:
        raise ValueError("prepaper independent recomputation did not pass")

    if offline["cross_checks"] != {
        **offline["cross_checks"],
        "formal_status": "VALID-MIXED",
        "formal_endpoint_qualified": 121,
        "formal_complete_contract": 0,
        "confidence_inversion_boundary_checks": "PASS",
    }:
        raise ValueError("offline-extension cross-check drift")
    if offline["command_activity_summary"]["projected_executed_max_abs"] != 0:
        raise ValueError("projected/executed identity drift")

    manifests = sorted(TRAIN_ROOT.rglob("manifest.json"))
    if len(manifests) != 208:
        raise ValueError(f"expected 208 training manifests, found {len(manifests)}")
    manifest_payloads = [read_json(path) for path in manifests]
    alpha_floor_count = sum(
        bool(row["learner_admissibility"]["alpha_at_floor"])
        for row in manifest_payloads
    )
    valid_count = sum(bool(row["valid"]) for row in manifest_payloads)
    training_tds_failures = sum(int(row["tds_failed_episodes"]) for row in manifest_payloads)

    break_even = [
        float(row["action_only_break_even"])
        for row in formal["threshold_sensitivity"]["break_even"]
    ]
    break_even_summary = {
        "min": min(break_even),
        "median": statistics.median(break_even),
        "max": max(break_even),
    }
    if break_even_summary != prepaper["probe02"]["observed"][
        "action_only_break_even"
    ]:
        raise ValueError("break-even independent recomputation drift")

    root_results = {
        f"probe_{index:02d}": read_json(
            RESULT_ROOT / f"root_cause_probe_{index:02d}/result.json"
        )
        for index in range(1, 11)
    }
    for key, row in root_results.items():
        if row.get("formal_artifacts_modified") is not False:
            raise ValueError(f"{key} did not preserve formal artifacts")

    expected_verdicts = {
        "probe_01": "REFUTES_JOINT_M_AND_D_CANCELLATION_MECHANISM",
        "probe_02": "RAW_PROPOSAL_ACTIVE_PROJECTION_MANUFACTURE_REFUTED",
        "probe_04": "TEMPORAL_TV_OBJECTIVE_BLINDNESS_SUPPORTED",
        "probe_08": "FEEDBACK_AMPLIFICATION_GENERALITY_SUPPORTED",
        "probe_09": "QUASISTATIC_ACTOR_SETPOINT_RMS_SUPPORTED",
        "probe_10": "INCONCLUSIVE",
    }
    observed_verdicts = {
        "probe_01": root_results["probe_01"]["decision"]["joint"],
        **{
            key: root_results[key]["decision"]["verdict"]
            for key in ("probe_02", "probe_04", "probe_08", "probe_09", "probe_10")
        },
    }
    if observed_verdicts != expected_verdicts:
        raise ValueError("selected exploratory verdict drift")

    command = offline["command_activity_summary"]
    bounds = [compact_bound(row) for row in offline["source_contrast_bounds"]]
    analysis: dict[str, Any] = {
        "schema_version": 1,
        "round": "R486",
        "parent_round": "R485",
        "status": "VALID-POSTHOC-INTAKE",
        "formal_artifacts_modified": False,
        "claim_tiers": {
            "formal_parent": "CLM-1525 remains the R485 result authority",
            "posthoc_supplement": "descriptive precision and sealed-data distributions",
            "exploratory_only": "checkpoint and recorded-path mechanism diagnostics",
        },
        "inputs": {
            "formal_analysis": FORMAL_ANALYSIS.relative_to(ROOT).as_posix(),
            "formal_analysis_sha256": formal_hash,
            "package_hashes": package_checks,
            "durable_probe_hashes": script_mirrors,
        },
        "formal_context": {
            "endpoint_qualified_policies": formal["learner_qualification"][
                "endpoint_qualified_count"
            ],
            "complete_contract_policies": formal["learner_qualification"][
                "complete_contract_passing_count"
            ],
            "action_only_break_even": break_even_summary,
            "break_even_definition": formal["threshold_sensitivity"][
                "break_even_definition"
            ],
        },
        "posthoc_supplement": {
            "status": "descriptive post-completion; not preregistered equivalence",
            "source_contrast_bounds": bounds,
            "pareto": offline["pareto_summary"],
            "endpoint_and_non_action_clean_policies": command[
                "endpoint_and_non_action_clean_policy_count"
            ],
            "projected_executed_max_abs": command["projected_executed_max_abs"],
            "command_activity_ratio_quantiles": {
                key: command[key]
                for key in (
                    "ratio_executed_M_rms",
                    "ratio_executed_D_rms",
                    "ratio_executed_M_tv",
                    "ratio_executed_D_tv",
                )
            },
        },
        "training_dynamics_disclosure": {
            "training_manifests": len(manifests),
            "valid_manifests": valid_count,
            "alpha_at_floor_count": alpha_floor_count,
            "training_tds_failed_episodes": training_tds_failures,
            "interpretation": (
                "registered admissibility passed; alpha-floor prevalence is a "
                "training-dynamics limitation, not convergence or optimality evidence"
            ),
        },
        "exploratory_diagnostics": {
            "status": "post-hoc; Discussion or supplement only",
            "selected_verdicts": observed_verdicts,
            "projection_tv": root_results["probe_02"]["decision"],
            "previous_action_grid": {
                "selection": root_results["probe_08"]["selection"],
                "decision": root_results["probe_08"]["decision"],
            },
            "quasi_static_rms": {
                "selection": root_results["probe_09"]["lineage"][
                    "checkpoint_identity"
                ],
                "decision": root_results["probe_09"]["decision"],
                "profiles": root_results["probe_09"]["profiles"],
            },
            "fixed_previous_intervention": {
                "selection": root_results["probe_10"]["selection"],
                "decision": root_results["probe_10"]["decision"],
                "profiles": root_results["probe_10"]["profiles"],
            },
            "excluded_label": (
                "probe 03 CHANNEL_SCALING_PRIMARY_CAUSE_SUPPORTED is overstrong; "
                "decoder scaling may shape M/D TV asymmetry only"
            ),
        },
        "independent_recomputation": observed_audit_decisions,
        "stay_out": [
            "preregistered equivalence or zero-effect claim",
            "closed-loop causal mechanism or repair claim",
            "full-208 mechanism prevalence",
            "actuator energy, wear, fatigue, thermal, hardware-harm or safety claim",
            "topology, deployment, convergence or optimality claim",
        ],
    }
    assert_finite(analysis, "analysis")
    write_stable_json(RESULT_ROOT / "analysis.json", analysis)
    json_hashes = write_json_sidecars()

    output = RESULT_ROOT / "analysis.json"
    output_hash = verify_sidecar(output)
    print(
        json.dumps(
            {
                "status": analysis["status"],
                "analysis_sha256": output_hash,
                "verified_packages": len(package_checks),
                "json_sidecars": len(json_hashes),
                "alpha_at_floor": f"{alpha_floor_count}/{len(manifests)}",
                "new_trajectories": 0,
            },
            indent=2,
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
