"""Throwaway R485 checkpoint probe: does previous-action feedback amplify raw TV?

Question
--------
For the outcome-blind first frozen policy (``an_cn_r0``, seed 501), is raw
action TV mainly generated by the actor's two previous-executed-action input
slots, conditional on the same sealed canonical observations?

Decision rule fixed before checkpoint loading
---------------------------------------------
Replay the deterministic actor twice: with the recorded previous executed
action and with those two slots set to zero at every step.  Feedback is a major
amplifier if zero-prev/actual raw TV <= 0.50 for every selected profile and
both M/D channels.  It is refuted if every ratio is >= 0.90.  Other outcomes
are inconclusive.  Actual-input replay must reproduce sealed raw action within
1e-6 or the probe aborts.

This is a local actor-input ablation on recorded observations, not a closed-loop
controller evaluation.  It does not show that a zero-prev controller is safe or
would preserve endpoints.

Usage
-----
``python probe_previous_action_feedback.py --self-check``
``python probe_previous_action_feedback.py``
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

import numpy as np
import torch


PROFILE_IDS = ("canary_eval_a", "canary_eval_b", "canary_eval_c", "canary_eval_d")
SUPPORT_RATIO_MAX = 0.50
REFUTE_RATIO_MIN = 0.90
REPLAY_TOLERANCE = 1.0e-6
EXPECTED_CHECKPOINT_SHA256 = "c5fec5e301cae22fbc71818523aca119d85bcb304b42f4dc87043618b072aaaa"


def find_root() -> Path:
    for parent in Path(__file__).resolve().parents:
        if (parent / "CLAUDE.md").is_file() and (parent / "pyproject.toml").is_file():
            return parent
    raise RuntimeError("repository root not found")


ROOT = find_root()
sys.path.insert(0, str(ROOT / "src"))

from andes_rl_kundur.agents.networks import GaussianActor  # noqa: E402


OUT_DIR = Path(__file__).resolve().parent
ATTEMPT_ROOT = (
    ROOT
    / "results/research_loop/r485_60hz_source_factorial/r485-formal-20260829-a"
)
CHECKPOINT_PATH = ATTEMPT_ROOT / "train/an_cn_r0/seed501/final.pt"
TRACE_ROOT = ATTEMPT_ROOT / "eval/same/an_cn_r0/seed501"


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def verified_sidecar(path: Path) -> dict[str, Any]:
    sidecar = Path(f"{path}.sha256")
    parts = sidecar.read_text(encoding="ascii").strip().split()
    if len(parts) < 2 or parts[1] != path.name:
        raise ValueError(f"invalid SHA256 sidecar: {sidecar}")
    actual = sha256_file(path)
    if actual != parts[0].lower():
        raise ValueError(f"SHA256 mismatch: {path}")
    return {
        "path": path.relative_to(ROOT).as_posix(),
        "sidecar": sidecar.relative_to(ROOT).as_posix(),
        "sha256": actual,
        "verified": True,
    }


def path_tv(records: np.ndarray) -> np.ndarray:
    """Sum zero-to-first TV over shape (records, steps, agents, channels)."""

    total = np.zeros(2, dtype=float)
    for record in records:
        previous = np.zeros((4, 2), dtype=float)
        for current in record:
            total += np.abs(np.asarray(current, dtype=float) - previous).sum(axis=0)
            previous = current
    return total


def synthetic_self_check() -> dict[str, Any]:
    obs = np.arange(7, dtype=np.float32)
    previous = np.asarray([0.25, -0.25], dtype=np.float32)
    state = np.concatenate([obs, previous])
    zero_state = np.concatenate([obs, np.zeros(2, dtype=np.float32)])
    if state.shape != (9,) or not np.array_equal(state[-2:], previous):
        raise AssertionError("actor state layout self-check failed")
    if not np.array_equal(zero_state[:7], state[:7]) or np.any(zero_state[-2:] != 0.0):
        raise AssertionError("zero-prev ablation self-check failed")
    sequence = np.zeros((1, 2, 4, 2), dtype=float)
    sequence[0, 0, 0] = [0.2, -0.1]
    sequence[0, 1, 0] = [0.4, -0.2]
    tv = path_tv(sequence)
    if not np.allclose(tv, [0.4, 0.2], rtol=0.0, atol=1e-15):
        raise AssertionError("TV self-check failed")
    return {"state_dim": int(state.size), "tv": tv.tolist()}


def load_actors() -> tuple[list[GaussianActor], dict[str, Any], dict[str, Any]]:
    checkpoint_input = verified_sidecar(CHECKPOINT_PATH)
    if checkpoint_input["sha256"] != EXPECTED_CHECKPOINT_SHA256:
        raise ValueError("checkpoint hash differs from frozen expected value")
    payload = torch.load(str(CHECKPOINT_PATH), map_location="cpu", weights_only=True)
    if (
        payload.get("kind") != "r485-source-factorial"
        or payload.get("arm_id") != "an_cn_r0"
        or int(payload.get("seed", -1)) != 501
        or payload.get("stage") != "final"
    ):
        raise ValueError("checkpoint identity mismatch")
    members = payload.get("members")
    if not isinstance(members, list) or len(members) != 4:
        raise ValueError("checkpoint must contain four members")
    actors: list[GaussianActor] = []
    for member in members:
        actor = GaussianActor(9, 2, [128, 128, 128, 128]).cpu().eval()
        actor.load_state_dict(member["actor"])
        actors.append(actor)
    return actors, payload, checkpoint_input


def load_profile(path: Path, checkpoint_sha: str) -> tuple[np.ndarray, np.ndarray, np.ndarray, dict[str, Any]]:
    input_row = verified_sidecar(path)
    payload = json.loads(path.read_text(encoding="utf-8"))
    records = payload.get("records")
    if not isinstance(records, list) or len(records) != 6:
        raise ValueError(f"expected 6 records: {path}")
    observations = np.zeros((6, 150, 4, 7), dtype=np.float32)
    previous = np.zeros((6, 150, 4, 2), dtype=np.float32)
    saved_raw = np.zeros((6, 150, 4, 2), dtype=np.float32)
    for record_index, record in enumerate(records):
        if record.get("checkpoint_sha256") != checkpoint_sha:
            raise ValueError("trace checkpoint lineage mismatch")
        steps = record.get("steps")
        if not isinstance(steps, list) or len(steps) != 150:
            raise ValueError(f"expected 150 steps: {path}")
        prior = np.zeros((4, 2), dtype=np.float32)
        for step_index, step in enumerate(steps):
            observations[record_index, step_index] = np.asarray(
                step["canonical_observation"], dtype=np.float32
            )
            previous[record_index, step_index] = prior
            saved_raw[record_index, step_index] = np.asarray(
                step["raw_action_norm"], dtype=np.float32
            )
            prior = np.asarray(step["projected_action_norm"], dtype=np.float32)
    return observations, previous, saved_raw, input_row


def actor_outputs(
    actors: list[GaussianActor], observations: np.ndarray, previous: np.ndarray
) -> np.ndarray:
    output = np.zeros((*observations.shape[:3], 2), dtype=np.float32)
    flat_obs = observations.reshape(-1, 4, 7)
    flat_previous = previous.reshape(-1, 4, 2)
    flat_output = output.reshape(-1, 4, 2)
    with torch.no_grad():
        for agent_index, actor in enumerate(actors):
            states = np.concatenate(
                [flat_obs[:, agent_index], flat_previous[:, agent_index]], axis=1
            ).astype(np.float32)
            flat_output[:, agent_index] = (
                actor.deterministic(torch.from_numpy(states)).cpu().numpy().astype(np.float32)
            )
    return output


def summarize_profile(
    profile_id: str, actors: list[GaussianActor], checkpoint_sha: str
) -> tuple[dict[str, Any], dict[str, Any]]:
    observations, previous, saved_raw, input_row = load_profile(
        TRACE_ROOT / f"{profile_id}.json", checkpoint_sha
    )
    replayed = actor_outputs(actors, observations, previous)
    replay_error = float(np.max(np.abs(replayed - saved_raw)))
    if replay_error > REPLAY_TOLERANCE:
        raise AssertionError(f"sealed raw-action replay mismatch: {replay_error}")
    zero_previous = np.zeros_like(previous)
    zero_prev_raw = actor_outputs(actors, observations, zero_previous)
    actual_tv = path_tv(saved_raw)
    zero_tv = path_tv(zero_prev_raw)
    return {
        "profile_id": profile_id,
        "actual_raw_tv": {"M": float(actual_tv[0]), "D": float(actual_tv[1])},
        "zero_prev_raw_tv": {"M": float(zero_tv[0]), "D": float(zero_tv[1])},
        "zero_prev_to_actual_tv_ratio": {
            "M": float(zero_tv[0] / actual_tv[0]),
            "D": float(zero_tv[1] / actual_tv[1]),
        },
        "sealed_raw_replay_max_abs_error": replay_error,
        "zero_prev_raw_rms": float(np.sqrt(np.mean(np.square(zero_prev_raw)))),
        "actual_raw_rms": float(np.sqrt(np.mean(np.square(saved_raw)))),
    }, input_row


def decide(rows: list[dict[str, Any]]) -> dict[str, Any]:
    ratios = [
        row["zero_prev_to_actual_tv_ratio"][channel]
        for row in rows
        for channel in ("M", "D")
    ]
    supported = all(value <= SUPPORT_RATIO_MAX for value in ratios)
    refuted = all(value >= REFUTE_RATIO_MIN for value in ratios)
    verdict = (
        "PREVIOUS_ACTION_FEEDBACK_MAJOR_AMPLIFIER_SUPPORTED"
        if supported
        else "PREVIOUS_ACTION_FEEDBACK_MAJOR_AMPLIFIER_REFUTED"
        if refuted
        else "INCONCLUSIVE"
    )
    return {"verdict": verdict, "support_criteria_met": supported, "refute_criteria_met": refuted}


def write_outputs(result: dict[str, Any]) -> None:
    result_path = OUT_DIR / "result.json"
    report_path = OUT_DIR / "REPORT.md"
    sums_path = OUT_DIR / "SHA256SUMS"
    result_path.write_text(
        json.dumps(result, indent=2, sort_keys=True, allow_nan=False) + "\n",
        encoding="utf-8",
    )
    lines = [
        "# R485 root-cause probe 05: previous-action feedback",
        "",
        "> Scratch post-hoc checkpoint diagnostic; not registered R485 evidence.",
        "",
        f"**Decision:** `{result['decision']['verdict']}`",
        "",
        "| Profile | zero-prev/actual M TV | zero-prev/actual D TV | replay error |",
        "|---|---:|---:|---:|",
    ]
    for row in result["profiles"]:
        ratio = row["zero_prev_to_actual_tv_ratio"]
        lines.append(
            f"| {row['profile_id']} | {ratio['M']:.3f} | {ratio['D']:.3f} | "
            f"{row['sealed_raw_replay_max_abs_error']:.3e} |"
        )
    lines.extend(
        [
            "",
            "The zero-prev ablation freezes observations and changes only two actor input",
            "slots. It is not a closed-loop controller or endpoint counterfactual.",
            "",
        ]
    )
    report_path.write_text("\n".join(lines), encoding="utf-8")
    hashed = [Path(__file__).resolve(), result_path, report_path]
    sums_path.write_text(
        "".join(f"{sha256_file(path)}  {path.name}\n" for path in hashed),
        encoding="ascii",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--self-check", action="store_true")
    args = parser.parse_args()
    torch.set_num_threads(1)
    self_check = synthetic_self_check()
    if args.self_check:
        print(json.dumps({"self_check": "PASS", "details": self_check}, indent=2))
        return 0

    actors, payload, checkpoint_input = load_actors()
    profiles: list[dict[str, Any]] = []
    trace_inputs: list[dict[str, Any]] = []
    for profile_id in PROFILE_IDS:
        row, input_row = summarize_profile(
            profile_id, actors, str(checkpoint_input["sha256"])
        )
        profiles.append(row)
        trace_inputs.append(input_row)
    result = {
        "schema_version": "r485_root_cause_probe_05_v1",
        "scope": "scratch_posthoc_checkpoint_diagnostic",
        "formal_artifacts_modified": False,
        "question": "Does previous-executed-action actor feedback materially amplify raw TV?",
        "thresholds": {
            "support_zero_prev_to_actual_ratio_max": SUPPORT_RATIO_MAX,
            "refute_zero_prev_to_actual_ratio_min": REFUTE_RATIO_MIN,
            "replay_tolerance": REPLAY_TOLERANCE,
        },
        "lineage": {
            "checkpoint": checkpoint_input,
            "checkpoint_identity": {
                "kind": payload["kind"],
                "arm_id": payload["arm_id"],
                "seed": payload["seed"],
                "stage": payload["stage"],
            },
            "trace_inputs": trace_inputs,
        },
        "self_check": self_check,
        "profiles": profiles,
    }
    result["decision"] = decide(profiles)
    write_outputs(result)
    print(json.dumps({"decision": result["decision"], "profiles": profiles}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
