"""Render memory/STATE.md from claims + rounds + handoffs."""
from __future__ import annotations
import argparse
import datetime as dt
import re
import sys
from collections import Counter
from pathlib import Path
from typing import Any

import yaml

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)


def _load_claims(claims_dir: Path) -> list[dict[str, Any]]:
    claims: list[dict[str, Any]] = []
    for path in sorted(claims_dir.glob("CLM-*.md")):
        match = FRONTMATTER_RE.match(path.read_text(encoding="utf-8"))
        if not match:
            continue
        meta = yaml.safe_load(match.group(1)) or {}
        claims.append(meta)
    return claims


def _latest_round(rounds_dir: Path) -> str | None:
    rounds = [p.name for p in rounds_dir.iterdir() if p.is_dir() and p.name.startswith("R")]
    if not rounds:
        return None
    return sorted(rounds, key=lambda r: int(r.lstrip("R")))[-1]


def _latest_handoff(handoffs_dir: Path) -> str | None:
    files = sorted(handoffs_dir.glob("*.md"))
    return files[-1].name if files else None


def _format_claim_line(claim: dict[str, Any]) -> str:
    cid = claim["id"]
    trust = claim.get("trust", "?")
    statement = (claim.get("statement") or "").strip().splitlines()[0]
    round_label = claim.get("round")
    suffix = f" ({round_label})" if round_label else ""
    return f"- {cid} [{trust}] {statement}{suffix}"


def render_state(
    claims_dir: Path, rounds_dir: Path, handoffs_dir: Path, out_path: Path
) -> None:
    claims = _load_claims(claims_dir)
    current = [c for c in claims if c.get("status") == "current"]

    headlines = [c for c in current if "headline" in (c.get("tags") or [])]
    decisions = [c for c in current if c.get("type") == "decision"]

    type_counts = Counter(c.get("type", "?") for c in claims)
    stats_line = (
        f"{len(claims)} claims "
        f"({type_counts.get('finding', 0)} finding / "
        f"{type_counts.get('decision', 0)} decision / "
        f"{type_counts.get('correction', 0)} correction), "
        f"{sum(1 for p in rounds_dir.iterdir() if p.is_dir())} rounds"
    )

    latest_round = _latest_round(rounds_dir) or "(none)"
    latest_handoff = _latest_handoff(handoffs_dir) or "(none)"
    now = dt.datetime.now().strftime("%Y-%m-%d %H:%M")

    lines: list[str] = []
    lines.append(f"# Project State — auto-rendered {now}\n")
    lines.append("> Do not edit this file. Regenerate via `python memory/tools/render.py`.\n")
    lines.append("## Current Headlines (status=current, tags=headline)\n")
    if headlines:
        for c in headlines:
            lines.append(_format_claim_line(c))
    else:
        lines.append("(none)")
    lines.append("")
    lines.append("## Open Decisions (type=decision, status=current)\n")
    if decisions:
        for c in decisions:
            lines.append(_format_claim_line(c))
    else:
        lines.append("(none)")
    lines.append("")
    lines.append("## Latest Round\n")
    lines.append(
        f"{latest_round} — see `memory/rounds/{latest_round}/verdict.md`"
        if latest_round != "(none)"
        else "(no rounds yet)"
    )
    lines.append("")
    lines.append("## Most Recent Handoff\n")
    lines.append(
        f"`memory/handoffs/{latest_handoff}`"
        if latest_handoff != "(none)"
        else "(no handoffs yet)"
    )
    lines.append("")
    lines.append("## Stats\n")
    lines.append(stats_line)
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Render memory/STATE.md")
    base = Path(__file__).parent.parent
    parser.add_argument("--claims-dir", type=Path, default=base / "claims")
    parser.add_argument("--rounds-dir", type=Path, default=base / "rounds")
    parser.add_argument("--handoffs-dir", type=Path, default=base / "handoffs")
    parser.add_argument("--out", type=Path, default=base / "STATE.md")
    args = parser.parse_args()
    render_state(args.claims_dir, args.rounds_dir, args.handoffs_dir, args.out)
    print(f"Rendered {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
