"""Regenerate ICEMS 2026 result macros and vector figures from frozen evidence."""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.lines import Line2D


PAPER_DIR = Path(__file__).resolve().parent
REPO_ROOT = PAPER_DIR.parents[1]
FIGURE_DIR = PAPER_DIR / "figures"


def load_json(relative_path: str) -> dict:
    with (REPO_ROOT / relative_path).open(encoding="utf-8") as stream:
        return json.load(stream)


def contrast_endpoint(summary: dict, endpoint: str) -> tuple[float, float, float]:
    contrasts = summary["paired_bootstrap"]["contrasts"]
    contrast = next(iter(contrasts.values()))
    estimate = contrast["endpoints"][endpoint]["ratio_of_means_percent"]
    low, high = estimate["percentile_95_interval"]
    return float(estimate["point"]), float(low), float(high)


def format_signed(value: float, digits: int = 2) -> str:
    return f"{value:+.{digits}f}"


def write_result_macros(
    r274: dict, r275: dict, r277: dict, r278_repair: dict
) -> None:
    rows = {
        "SlowIae": contrast_endpoint(r274, "vsg_mean_iae_hz_s"),
        "SlowFinal": contrast_endpoint(r274, "final_window_common_abs_mean_hz"),
        "FastRocof": contrast_endpoint(r275, "max_abs_rocof_hz_s"),
        "FastPeak": contrast_endpoint(r275, "worst_bus_peak_abs_hz"),
        "FastSync": contrast_endpoint(r275, "normalized_sync_loss_hz2"),
        "FastArea": contrast_endpoint(r275, "fast_inter_area_iae_hz_s"),
        "OracleSync": contrast_endpoint(r277, "normalized_sync_loss_hz2"),
        "OracleArea": contrast_endpoint(r277, "fast_inter_area_iae_hz_s"),
    }
    repaired = r278_repair["decision"]
    for key, endpoint, section in (
        ("PilotSync", "normalized_sync_loss_hz2", "primary_endpoints"),
        ("PilotArea", "fast_inter_area_iae_hz_s", "primary_endpoints"),
        ("PilotRocof", "max_abs_rocof_hz_s", "fast_guards"),
        ("PilotPeak", "worst_bus_peak_abs_hz", "fast_guards"),
        ("PilotIae", "vsg_mean_iae_hz_s", "slow_guards"),
        ("PilotFinal", "final_window_common_abs_mean_hz", "slow_guards"),
    ):
        source = repaired[section][endpoint]
        point = float(source["point_percent"])
        high = float(source["ci_upper_percent"])
        # The repair preserves the original paired-bootstrap intervals.
        original = r278_repair["unchanged_primary_contrast"].get(endpoint)
        if original is not None:
            low = float(original["ratio_of_means_percent"]["percentile_95_interval"][0])
        else:
            r278_summary = load_json(
                "results/r278_icems_residual_pilot_s49/"
                "icems_residual_pilot_summary.json"
            )
            _, low, _ = contrast_endpoint(r278_summary, endpoint)
        rows[key] = (point, low, high)

    repair = r278_repair["repair"]
    macro_lines = [
        "% Generated by build_figures.py from frozen R274--R278 summaries.",
        r"\newcommand{\PilotVerdict}{PILOT-NO-GO}",
    ]
    for name, (point, low, high) in rows.items():
        macro_lines.append(
            rf"\newcommand{{\{name}Effect}}{{{format_signed(point)}}}"
        )
        macro_lines.append(
            rf"\newcommand{{\{name}CI}}{{[{format_signed(low)}, "
            rf"{format_signed(high)}]}}"
        )
    macro_lines.extend(
        [
            r"\newcommand{\ZeroSumTolerance}{1.220703\times10^{-4}}",
            r"\newcommand{\ZeroSumObserved}{4.577637\times10^{-5}}",
            r"\newcommand{\PilotMaxCommand}{0.313497}",
            r"\newcommand{\PilotMinSoc}{0.486074}",
            r"\newcommand{\PilotMaxSoc}{0.511454}",
            "",
        ]
    )
    (PAPER_DIR / "generated_results.tex").write_text(
        "\n".join(macro_lines), encoding="utf-8"
    )


def draw_forest_panel(
    axis: plt.Axes,
    rows: list[tuple[str, float, float, float, str]],
    xlim: tuple[float, float],
    title: str,
) -> None:
    palette = {
        "slow": "#0072B2",
        "fast": "#009E73",
        "oracle": "#7A7A7A",
        "policy": "#D55E00",
    }
    markers = {"slow": "o", "fast": "s", "oracle": "D", "policy": "o"}
    y_values = list(range(len(rows)))[::-1]
    for y, (label, point, low, high, group) in zip(y_values, rows, strict=True):
        face = "white" if label.startswith("Early inter-area") and group == "policy" else palette[group]
        axis.errorbar(
            point,
            y,
            xerr=[[point - low], [high - point]],
            fmt=markers[group],
            markersize=5.2,
            markerfacecolor=face,
            markeredgecolor=palette[group],
            markeredgewidth=1.1,
            ecolor=palette[group],
            elinewidth=1.1,
            capsize=2.2,
            zorder=3,
        )
    axis.axvline(0, color="#333333", linewidth=0.9)
    axis.set_yticks(y_values, [row[0] for row in rows])
    axis.set_xlim(*xlim)
    axis.set_title(title, loc="left", fontweight="bold", pad=4)
    axis.grid(axis="x", color="#D9D9D9", linewidth=0.5)
    axis.set_axisbelow(True)
    axis.spines[["top", "right", "left"]].set_visible(False)
    axis.tick_params(axis="y", length=0, pad=3)
    axis.set_xlabel("Effect relative to matched reference (%)")


def write_paired_effect_figure(r274: dict, r275: dict, r277: dict, r278: dict) -> None:
    classical = [
        ("Mean-frequency IAE", *contrast_endpoint(r274, "vsg_mean_iae_hz_s"), "slow"),
        (
            "Final-window common error",
            *contrast_endpoint(r274, "final_window_common_abs_mean_hz"),
            "slow",
        ),
        ("Maximum RoCoF", *contrast_endpoint(r275, "max_abs_rocof_hz_s"), "fast"),
        (
            "Worst-bus peak",
            *contrast_endpoint(r275, "worst_bus_peak_abs_hz"),
            "fast",
        ),
        (
            "Synchronization loss",
            *contrast_endpoint(r275, "normalized_sync_loss_hz2"),
            "fast",
        ),
        (
            "Early inter-area IAE",
            *contrast_endpoint(r275, "fast_inter_area_iae_hz_s"),
            "fast",
        ),
    ]
    differential = [
        (
            "Oracle synchronization",
            *contrast_endpoint(r277, "normalized_sync_loss_hz2"),
            "oracle",
        ),
        (
            "Oracle inter-area IAE",
            *contrast_endpoint(r277, "fast_inter_area_iae_hz_s"),
            "oracle",
        ),
        (
            "Policy synchronization",
            *contrast_endpoint(r278, "normalized_sync_loss_hz2"),
            "policy",
        ),
        (
            "Early inter-area policy",
            *contrast_endpoint(r278, "fast_inter_area_iae_hz_s"),
            "policy",
        ),
    ]

    plt.rcParams.update(
        {
            "font.family": "serif",
            "font.serif": ["Times New Roman", "Times", "DejaVu Serif"],
            "font.size": 8.0,
            "axes.titlesize": 8.4,
            "axes.labelsize": 8.0,
            "xtick.labelsize": 8.0,
            "ytick.labelsize": 8.0,
            "legend.fontsize": 8.0,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )
    figure, axes = plt.subplots(
        1,
        2,
        figsize=(7.15, 2.75),
        gridspec_kw={"width_ratios": [1.15, 1.0], "wspace": 0.56},
    )
    draw_forest_panel(
        axes[0],
        classical,
        (-82, 5),
        "(a) Supported classical coordinates",
    )
    draw_forest_panel(
        axes[1],
        differential,
        (-40, 10),
        "(b) Differential opportunity and policy",
    )
    legend = [
        Line2D(
            [0],
            [0],
            marker="o",
            color="none",
            markerfacecolor="#0072B2",
            markeredgecolor="#0072B2",
            label="Slow restoration",
        ),
        Line2D(
            [0],
            [0],
            marker="s",
            color="none",
            markerfacecolor="#009E73",
            markeredgecolor="#009E73",
            label="Fast common pulse",
        ),
        Line2D(
            [0],
            [0],
            marker="D",
            color="none",
            markerfacecolor="#7A7A7A",
            markeredgecolor="#7A7A7A",
            label="Outcome-seeing oracle",
        ),
        Line2D(
            [0],
            [0],
            marker="o",
            color="none",
            markerfacecolor="#D55E00",
            markeredgecolor="#D55E00",
            label="Shared policy",
        ),
        Line2D(
            [0],
            [0],
            marker="o",
            color="none",
            markerfacecolor="white",
            markeredgecolor="#D55E00",
            label="Primary gate not cleared",
        ),
    ]
    figure.legend(
        handles=legend,
        loc="lower center",
        bbox_to_anchor=(0.5, -0.01),
        ncol=3,
        frameon=False,
        handletextpad=0.4,
        columnspacing=1.0,
    )
    figure.subplots_adjust(left=0.21, right=0.985, top=0.88, bottom=0.25)
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    figure.savefig(FIGURE_DIR / "paired_effects.pdf", bbox_inches="tight")
    plt.close(figure)


def main() -> None:
    r274 = load_json(
        "results/r274_prospective_active_power_authority/"
        "active_power_authority_summary.json"
    )
    r275 = load_json(
        "results/r275_fast_md_authority/fast_md_authority_summary.json"
    )
    r277 = load_json(
        "results/r277_learning_gap_oracle/learning_gap_oracle_summary.json"
    )
    r278 = load_json(
        "results/r278_icems_residual_pilot_s49/icems_residual_pilot_summary.json"
    )
    r278_repair = load_json("memory/rounds/R278/analysis_repair.json")
    write_result_macros(r274, r275, r277, r278_repair)
    write_paired_effect_figure(r274, r275, r277, r278)


if __name__ == "__main__":
    main()
